version: "3.8"
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    command: streamlit run /app/projetodash.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: uvicorn projetodash:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
