# Definir imagem base
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos necessários
COPY ./projetodash.py /app/projetodash.py
COPY ./requirements.txt /app/requirements.txt

# Instalar as dependências
RUN pip install --no-cache-dir -r /app/requirements.txt

# Comando para rodar o Streamlit
CMD ["streamlit", "run", "/app/projetodash.py"]

